version:  '3'
services:
  app:
      build: .
      restart: unless-stopped
      container_name: sk_rsi_bot
      volumes:
        - data:/usr/src/app/myapp/data_
      env_file:
        - .env

volumes:
  data:
